version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: password_username
      POSTGRES_PASSWORD: password_password
      POSTGRES_DB: password_database
    ports:
      - "5432:5432"
    expose:
      - 5432

